name: Container
on: push

jobs:
  docker-steps:
    runs-on: ubuntu-latest
    container:
      image: node:17-alpine3.13
    steps:
      - name: Log Node Version
        run: node -v
      - name: Step with Docker
        uses: docker://node:16-bullseye-slim
        with:
          entrypoint: "/bin/echo"
          args: "Hello World"
      - name: Log Node Version
        uses: docker://node:16-bullseye-slim
        with:
          entrypoint: /usr/local/bin/node
          args: -v
      - uses: actions/checkout@v1
      - name: Run a script      
        uses: docker://node:16-bullseye-slim
        with:
          entrypoint: ./entrypoint.sh
          args: "Welcome Sir"
  node-docker:
    runs-on: ubuntu-latest
    services: 
      app:
        image: gpras/node-log-exporter:latest
        ports:
          - 3002:3001
      mongo:
        image: mongo
        ports:
          - "27017:27017"
    steps:
      - name: Generate CSV file
        run: "curl -X GET http://localhost:3002/logs/export/csv -H 'Content-Type: application/json'"      