name: Container
on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    services: 
      app:
        image: gpras/node-log-exporter:latest
        ports:
          - 3002:3001
      mongo:
        image: mongo
        ports:
          - "27017:27017"
    steps:
      - name: Generate CSV file
        run: "curl -X GET http://localhost:3002/logs/export/csv -H 'Content-Type: application/json'"
      - name: See Output
        run: ls -la /usr/src/app/output